name: CI - VishalMusic Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    name: Setup & Run VishalMusic
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      # 4. Create .env from GitHub secrets
      - name: Create .env file
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "OWNER_ID=${{ secrets.OWNER_ID }}" >> .env
          echo "LOGGER_ID=${{ secrets.LOGGER_ID }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "STRING_SESSION=${{ secrets.STRING_SESSION }}" >> .env
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> .env
          echo "COOKIE_URL=${{ secrets.COOKIE_URL }}" >> .env
          echo "DEEP_API=${{ secrets.DEEP_API }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      # 5. Run bot
      - name: Run VishalMusic Bot
        run: |
          python3 -m VISHALMUSIC
