name: CI - VishalMusic Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-run:
    name: Lint, Test & Smoke Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8 black isort
          flake8 .
          black --check .

      - name: Run tests
        run: |
          pytest || echo "No tests found, skipping"

      - name: Create .env file
        run: |
          echo "API_ID=${{ secrets.API_ID }}" >> .env
          echo "API_HASH=${{ secrets.API_HASH }}" >> .env
          echo "OWNER_ID=${{ secrets.OWNER_ID }}" >> .env
          echo "LOGGER_ID=${{ secrets.LOGGER_ID }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "STRING_SESSION=${{ secrets.STRING_SESSION }}" >> .env
          echo "MONGO_DB_URI=${{ secrets.MONGO_DB_URI }}" >> .env
          echo "COOKIE_URL=${{ secrets.COOKIE_URL }}" >> .env
          echo "DEEP_API=${{ secrets.DEEP_API }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "API_URL=${{ secrets.API_URL }}" >> .env

      - name: Run bot (smoke test)
        run: |
          python -m VISHALMUSIC & sleep 5; pkill -f VISHALMUSIC
